### ISSUE TITLE
Discrete methylation level

### ISSUE THREAD

**Issue by xiweiwu** [hacone/AgIn#3]
Dear Yuta,

Does AgIn software support the Discrete methylation level (DML) analysis described in your original paper? If so, what is the parameter setting for this analysis? It seems that the class.wig file only has 0/1 state of each CG site. 

Thanks a lot,

**Comment by hacone** [comment]
Hi xiweiwu, please pass the option `-c` to produce a multi-level prediction file.

**Comment by xiweiwu** [comment]
Thanks, Yuta.

The AgIn gives an error ([AgIn$] ERROR: parseOpt: ill-formed arguments) with -c option Please see below. Could you let me know if it is run correctly?

/Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/modifications.csv -f /Users/Taehyuk/Desktop/pDmeth.fa -o /Users/Taehyuk/Desktop/test -b P5C3_HdrR -g -0.88 -l 50 predict -c 
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>

**Comment by hacone** [comment]
The task name (`predict` in this case) must be the last argument.
Thank you.

**Comment by tay45** [comment]
Hi Yuta,

## The -c option is not working at any positions in command line. Please see what I attached at below. Could you please give me a command line as an example? Thank you!

Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -g -0.88 -l 50 -c predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -g -0.88 -c -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -c -g -0.88 -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -c -b P5C3_HdrR -g -0.88 -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -c -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -g -0.88 -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -c -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -g -0.88 -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments
AgIn: <explanation>
Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -c -i /Users/Taehyuk/Desktop/AgIn_analysis/modifications.csv -f /Users/Taehyuk/Desktop/AgIn_analysis/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn_analysis/test -b P5C3_HdrR -g -0.88 -l 50 predict
[AgIn$] ERROR: parseOpt: ill-formed arguments

**Comment by hacone** [comment]
Your command line seems OK. Maybe the version you are running is not the latest.
Please clone the latest repository by `git clone`, and then make the executable by running `bin/sbt package-dist`. If this doesn't solve the problem, I will update this to produce more informative error message and to track down what is wrong.

**Comment by xogur** [comment]
I did try it, but it seems not working. 

Taehyuks-MacBook-Pro:~ Taehyuk$ git clone https://github.com/hacone/AgIn.git AgIn
Cloning into 'AgIn'...
remote: Counting objects: 456, done.
remote: Total 456 (delta 0), reused 0 (delta 0), pack-reused 456
Receiving objects: 100% (456/456), 10.82 MiB | 963.00 KiB/s, done.
Resolving deltas: 100% (159/159), done.
Checking connectivity... done.
Taehyuks-MacBook-Pro:~ Taehyuk$ cd AgIn
Taehyuks-MacBook-Pro:AgIn Taehyuk$ bin/sbt package-dist
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
Taehyuks-MacBook-Pro:AgIn Taehyuk$ cd bin
Taehyuks-MacBook-Pro:bin Taehyuk$ bin/sbt package-dist
-bash: bin/sbt: No such file or directory
Taehyuks-MacBook-Pro:bin Taehyuk$ sbt package-dist
[info] Set current project to bin (in build file:/Users/Taehyuk/AgIn/bin/)
[error] Not a valid command: package-dist
[error] Not a valid project ID: package-dist
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: package-dist (similar: package-bin, package-src, package-doc)
[error] package-dist
[error]             ^
Taehyuks-MacBook-Pro:bin Taehyuk$

**Comment by tay45** [comment]
I've cloned the latest one, and it seems to be working!
I can generate four output files such as;
1. test.gff
2. test_class.wig
3. test_continuous_class.wig
4. test_coverage.wig
I think #3 file is the multi-level prediction file what you said. Is it right? If yes, does 1.0 predict 100% of methylation? Thank you!
